name: Release (Nix build)

on:
  release:
    types: [published]

jobs:
  nix-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v3
      - uses: cachix/cachix-action@v15
        with:
          name: mycache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#niri --print-build-logs
